[2025-07-30T19:24:18.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T19:24:18.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburant_etl_dag.extract_data manual__2025-07-30T19:24:17.241505+00:00 [queued]>
[2025-07-30T19:24:18.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburant_etl_dag.extract_data manual__2025-07-30T19:24:17.241505+00:00 [queued]>
[2025-07-30T19:24:18.655+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-30T19:24:18.661+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-30 19:24:17.241505+00:00
[2025-07-30T19:24:18.665+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T19:24:18.666+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2025-07-30T19:24:18.665+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'carburant_etl_dag', 'extract_data', 'manual__2025-07-30T19:24:17.241505+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_carburant.py', '--cfg-path', '/tmp/tmpdaorhj_r']
[2025-07-30T19:24:18.667+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_data
[2025-07-30T19:24:18.676+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-30T19:24:18.696+0000] {task_command.py:426} INFO - Running <TaskInstance: carburant_etl_dag.extract_data manual__2025-07-30T19:24:17.241505+00:00 [running]> on host 19656c0da80c
[2025-07-30T19:24:18.738+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='carburant_etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T19:24:17.241505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T19:24:17.241505+00:00'
[2025-07-30T19:24:18.739+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T19:24:19.072+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T19:24:19.073+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/extract/download_data.py", line 16, in download_xml
    os.makedirs(DATA_DIR, exist_ok=True)
  File "<frozen os>", line 210, in makedirs
  File "<frozen posixpath>", line 103, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-07-30T19:24:19.086+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=carburant_etl_dag, task_id=extract_data, run_id=manual__2025-07-30T19:24:17.241505+00:00, execution_date=20250730T192417, start_date=20250730T192418, end_date=20250730T192419
[2025-07-30T19:24:19.091+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract_data (expected str, bytes or os.PathLike object, not NoneType; 193)
[2025-07-30T19:24:19.103+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T19:24:19.116+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T19:24:19.117+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
